In [ ]:
import pandas as pd

In [ ]:
df17=pd.read_csv('17.용인시_소상공인_매출정보.csv')

In [ ]:
df17.columns

Index(['gid', 'ws_cnt', 'found_age_1', 'found_age_2', 'found_age_3',
       'found_age_4', 'found_age_5', 'found_age_6', 'runout_cnt',
       'smbiz_yn_cnt', 'rpr_per_gender_m', 'rpr_per_gender_f',
       'rpr_per_age_bin_10', 'rpr_per_age_bin_20', 'rpr_per_age_bin_30to50',
       'rpr_per_age_bin_50over', 'sme_loan_cnt', 'sme_loan_y_1',
       'sme_loan_y_2', 'sme_loan_y_3', 'sme_loan_y_4', 'sme_loan_y_5',
       'sme_loan_y_6', 'sales_est_amt_201703', 'sales_est_amt_201706',
       'sales_est_amt_201709', 'sales_est_amt_201712', 'sales_est_amt_201803',
       'sales_est_amt_201806', 'sales_est_amt_201809', 'sales_est_amt_201812',
       'sales_est_amt_201903', 'sales_est_amt_201906', 'sales_est_amt_201909',
       'sales_est_amt_201912', 'sales_est_amt_202003', 'sales_est_amt_202006',
       'sales_est_amt_202009', 'age10_ratio', 'age20_ratio', 'age30_ratio',
       'age40_ratio', 'age50_ratio', 'age60_ratio', 'age70_ratio',
       'indcd_a_yn', 'indcd_b_yn', 'indcd_c_yn', 'indcd_d_yn', 'indcd_e_yn',
       'indcd_f_yn', 'indcd_g_yn', 'indcd_h_yn', 'indcd_i_yn', 'indcd_j_yn',
       'indcd_k_yn', 'indcd_l_yn', 'indcd_m_yn', 'indcd_n_yn', 'indcd_o_yn',
       'indcd_p_yn', 'indcd_q_yn', 'indcd_r_yn', 'indcd_s_yn', 'indcd_t_yn',
       'indcd_u_yn'],
      dtype='object')

In [ ]:
df17_1703= df17.loc[0:,[ 'sales_est_amt_201703','sme_loan_cnt',]]

In [ ]:
corr = df17_.corr(method = 'pearson')
corr

                      sales_est_amt_201703  sme_loan_cnt
sales_est_amt_201703              1.000000      0.843111
sme_loan_cnt                      0.843111      1.000000

In [ ]:
df17_= df17.loc[0:,['gid', 'sales_est_amt_201706','sme_loan_cnt',]]

In [ ]:
corr = df17_.corr(method = 'pearson')
corr

                      sales_est_amt_201706  sme_loan_cnt
sales_est_amt_201706              1.000000      0.846112
sme_loan_cnt                      0.846112      1.000000

In [ ]:
df17_= df17.loc[0:,['sales_est_amt_201709','sme_loan_cnt',]]
corr = df17_.corr(method = 'pearson')
corr

                      sales_est_amt_201709  sme_loan_cnt
sales_est_amt_201709              1.000000      0.848568
sme_loan_cnt                      0.848568      1.000000

In [ ]:
df17_1703.to_csv('./월별/df17_1703.csv') #csv파일로 생성

In [ ]:
df17_1703

     sales_est_amt_201703  sme_loan_cnt
0                    1682             2
1                    2563             3
2                    5180             3
3                    1645             5
4                     216             2
..                    ...           ...
802                   264             2
803                  1118             4
804                  1453             0
805                  1165             5
806                   336             2

[807 rows x 2 columns]

In [ ]:
#창업found_age와 대출 사이의 상관관계 
df17_ageloantotal= df17.loc[0:,[ 'found_age_1', 'found_age_2', 'found_age_3',
       'found_age_4', 'found_age_5', 'found_age_6','sme_loan_cnt', 'sme_loan_y_1',
       'sme_loan_y_2', 'sme_loan_y_3', 'sme_loan_y_4', 'sme_loan_y_5',
       'sme_loan_y_6',]]

In [ ]:
corrtotal=df17_ageloantotal.corr(method = 'pearson')
corrtotal

,found_age_1,found_age_2,found_age_3,found_age_4,found_age_5,found_age_6,sme_loan_cnt,sme_loan_y_1,sme_loan_y_2,sme_loan_y_3,sme_loan_y_4,sme_loan_y_5,sme_loan_y_6
found_age_1,1.000000,0.789351,0.753333,0.678665,0.666884,0.636626,0.745635,0.637862,0.647920,0.708374,0.720358,0.674359,0.579600
found_age_2,0.789351,1.000000,0.833387,0.763192,0.751564,0.745838,0.873413,0.682888,0.728519,0.801522,0.833397,0.791536,0.725171
found_age_3,0.753333,0.833387,1.000000,0.761452,0.697991,0.696421,0.827318,0.660319,0.668963,0.759342,0.812590,0.732715,0.676261
found_age_4,0.678665,0.763192,0.761452,1.000000,0.816994,0.819194,0.874680,0.653066,0.657480,0.773409,0.845876,0.783396,0.760526
found_age_5,0.666884,0.751564,0.697991,0.816994,1.000000,0.822202,0.870110,0.618945,0.672753,0.774127,0.836721,0.797766,0.750550
found_age_6,0.636626,0.745838,0.696421,0.819194,0.822202,1.000000,0.884705,0.588150,0.618853,0.756689,0.860639,0.800947,0.800672
sme_loan_cnt,0.745635,0.873413,0.827318,0.874680,0.870110,0.884705,1.000000,0.697030,0.738652,0.837527,0.952577,0.923622,0.903840
sme_loan_y_1,0.637862,0.682888,0.660319,0.653066,0.618945,0.588150,0.697030,1.000000,0.577483,0.634001,0.652492,0.582547,0.511930
sme_loan_y_2,0.647920,0.728519,0.668963,0.657480,0.672753,0.618853,0.738652,0.577483,1.000000,0.679465,0.686493,0.630228,0.553916
sme_loan_y_3,0.708374,0.801522,0.759342,0.773409,0.774127,0.756689,0.837527,0.634001,0.679465,1.000000,0.791799,0.727097,0.627406
sme_loan_y_4,0.720358,0.833397,0.812590,0.845876,0.836721,0.860639,0.952577,0.652492,0.686493,0.791799,1.000000,0.845364,0.799392
sme_loan_y_5,0.674359,0.791536,0.732715,0.783396,0.797766,0.800947,0.923622,0.582547,0.630228,0.727097,0.845364,1.000000,0.829419
sme_loan_y_6,0.579600,0.725171,0.676261,0.760526,0.750550,0.800672,0.903840,0.511930,0.553916,0.627406,0.799392,0.829419,1.000000

In [ ]:
corrtotal.head(6)

,found_age_1,found_age_2,found_age_3,found_age_4,found_age_5,found_age_6,sme_loan_cnt,sme_loan_y_1,sme_loan_y_2,sme_loan_y_3,sme_loan_y_4,sme_loan_y_5,sme_loan_y_6
found_age_1,1.000000,0.789351,0.753333,0.678665,0.666884,0.636626,0.745635,0.637862,0.647920,0.708374,0.720358,0.674359,0.579600
found_age_2,0.789351,1.000000,0.833387,0.763192,0.751564,0.745838,0.873413,0.682888,0.728519,0.801522,0.833397,0.791536,0.725171
found_age_3,0.753333,0.833387,1.000000,0.761452,0.697991,0.696421,0.827318,0.660319,0.668963,0.759342,0.812590,0.732715,0.676261
found_age_4,0.678665,0.763192,0.761452,1.000000,0.816994,0.819194,0.874680,0.653066,0.657480,0.773409,0.845876,0.783396,0.760526
found_age_5,0.666884,0.751564,0.697991,0.816994,1.000000,0.822202,0.870110,0.618945,0.672753,0.774127,0.836721,0.797766,0.750550
found_age_6,0.636626,0.745838,0.696421,0.819194,0.822202,1.000000,0.884705,0.588150,0.618853,0.756689,0.860639,0.800947,0.800672

# 20대 대표와 대출의 상관관계 ==> 대출은 하지만 대출 비용은 크지 않다!

In [ ]:
#20대 대표와 대출의 상관관계
df17_20= df17.loc[0:,[ 'rpr_per_age_bin_20','sme_loan_cnt', 'sme_loan_y_1',
       'sme_loan_y_2', 'sme_loan_y_3', 'sme_loan_y_4', 'sme_loan_y_5',
       'sme_loan_y_6',]]

In [ ]:
corr17_20 = df17_20.corr(method = 'pearson')
corr17_20

,rpr_per_age_bin_20,sme_loan_cnt,sme_loan_y_1,sme_loan_y_2,sme_loan_y_3,sme_loan_y_4,sme_loan_y_5,sme_loan_y_6
rpr_per_age_bin_20,1.000000,0.720219,0.568574,0.612777,0.687193,0.695481,0.669318,0.563093
sme_loan_cnt,0.720219,1.000000,0.697030,0.738652,0.837527,0.952577,0.923622,0.903840
sme_loan_y_1,0.568574,0.697030,1.000000,0.577483,0.634001,0.652492,0.582547,0.511930
sme_loan_y_2,0.612777,0.738652,0.577483,1.000000,0.679465,0.686493,0.630228,0.553916
sme_loan_y_3,0.687193,0.837527,0.634001,0.679465,1.000000,0.791799,0.727097,0.627406
sme_loan_y_4,0.695481,0.952577,0.652492,0.686493,0.791799,1.000000,0.845364,0.799392
sme_loan_y_5,0.669318,0.923622,0.582547,0.630228,0.727097,0.845364,1.000000,0.829419
sme_loan_y_6,0.563093,0.903840,0.511930,0.553916,0.627406,0.799392,0.829419,1.000000

In [ ]:
df17_foundrun= df17.loc[0:,[ 'found_age_1', 'found_age_2', 'found_age_3',
       'found_age_4', 'found_age_5', 'found_age_6','runout_cnt',]]

In [ ]:
corr17_foundrun = df17_foundrun.corr(method = 'pearson')
corr17_foundrun

,found_age_1,found_age_2,found_age_3,found_age_4,found_age_5,found_age_6,runout_cnt
found_age_1,1.000000,0.789351,0.753333,0.678665,0.666884,0.636626,0.664319
found_age_2,0.789351,1.000000,0.833387,0.763192,0.751564,0.745838,0.754536
found_age_3,0.753333,0.833387,1.000000,0.761452,0.697991,0.696421,0.721557
found_age_4,0.678665,0.763192,0.761452,1.000000,0.816994,0.819194,0.765781
found_age_5,0.666884,0.751564,0.697991,0.816994,1.000000,0.822202,0.775292
found_age_6,0.636626,0.745838,0.696421,0.819194,0.822202,1.000000,0.739250
runout_cnt,0.664319,0.754536,0.721557,0.765781,0.775292,0.739250,1.000000